name: Actualizar Datos de Liga

on:
  schedule:
    # Se ejecuta a las 09:00 UTC (Aprox 3:00 AM en Juárez/CDMX)
    - cron: '0 9 * * *'
  workflow_dispatch: # Permite ejecutarlo manualmente desde GitHub si quieres

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Instalar dependencias
      run: |
        pip install requests

    - name: Ejecutar script de actualización
      env:
        API_KEY_FOOTBALL: ${{ secrets.FOOTBALL_DATA_API_KEY }}
      run: python update_league_data.py

    - name: Guardar cambios en GitHub
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add liga_data.json
        git diff --quiet && git diff --staged --quiet || git commit -m "Actualización diaria de liga_data.json"
        git push
